version: '3.1'

services:
  blog_strapi_api:
    container_name: blog_strapi_api
    hostname: blog_strapi_api
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: blog_strapi
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/.blog_strapi:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432